version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001  
      - IMAGE_UPLOAD_PATH=/app/uploads
    volumes:
      - ./backend:/backend
      - ./backend/uploads:/app/uploads  
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
